### ISSUE TITLE
App permissions

### ISSUE THREAD

**Issue by gprst** [arduia/ProExpense#10]
The app seems to require a lot of permissions by default, for an offline expense management app. According to F-droid, the app requires to : 
- have full network access
- prevent phone from sleeping
- run at startup
- view network connections

I don't know much about Android development, perhaps these permissions are granted by default. And I am not saying the app is making use of these permissions ; I just feel like it would be more honest for a simple (and cool) offline app not to require these. :)

**Comment by arduia** [comment]
Feedback feature of the app use network access, also comments submitted by user are stored in free [server](https://www.heroku.com/) that must be awaken for few seconds in background. 

The app still need many things to meet user requirements. So, I added Feedback feature to get interaction with users.

**Comment by gprst** [comment]
Alriight, thank you for the clarification :)
