### ISSUE TITLE
Accessibility — font size and display size 

### ISSUE THREAD

**Issue by testuser51** [arduia/ProExpense#12]
Bug description
Not enough space between the text
![image](https://user-images.githubusercontent.com/53906414/94288035-a39a5d00-ff5f-11ea-974a-7311822a2f57.png)

Steps to reproduce:
Settings - Accessibility - font size and display size = largest
![image](https://user-images.githubusercontent.com/53906414/94287827-7352be80-ff5f-11ea-816a-52d13ef29588.png)

App Version: 0.1.2-beta

**Comment by arduia** [comment]
@testuser51 Thanks. I will fix it soon.

**Comment by arduia** [comment]
This issue is not longer exist cuz UI design is changed.
