### ISSUE TITLE
Blue Screen Appears. Nothing else shows

### ISSUE THREAD

**Issue by SArsalanK** [arduia/ProExpense#13]
![Screenshot_2020-09-29-16-41-04-194_com arduia expense](https://user-images.githubusercontent.com/2125947/94553936-b28c5280-0272-11eb-9438-01b50fafaa4b.jpg)

**Comment by arduia** [comment]
@SArsalanK Thanks. Will fix it soon.

**Comment by SArsalanK** [comment]
Great. Let me know!

**Comment by arduia** [comment]
@SArsalanK 
I have updated the latest app at [Play Store](https://play.google.com/store/apps/details?id=com.arduia.expense). You can play with new features such as Light/Dark Theme. I assume that this issue have already been fixed.

Thanks.
