### ISSUE TITLE
Can't add decimal numer

### ISSUE THREAD

**Issue by gianlucaalfa** [arduia/ProExpense#18]
I can't add amounts with comma or point. I can only add integer
MIUI 12 
release: v0.1.2-beta

**Comment by arduia** [comment]
@gianlucaalfa Hey Thanks for your feedback.

This Decimal number bug is already fixed in current version [v0.2.0-alpha1 ](https://github.com/arduia/ProExpense/commit/7b9c5faf4080e841b19081cf903553b39d134379) will be released at 20th December 2020. 

Please wait for next release!
