### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [arduia/ProExpense#23]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the settings page, the text and the ‘√’ overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
App version is 1.0.0, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="444" alt="bug-expense-2" src="https://user-images.githubusercontent.com/18572115/103154629-a2cdcd00-47d3-11eb-9b20-3af318b6fc58.png">

**Comment by arduia** [comment]
@franklinbill I will fix this issue soon. Thanks

New version is now available! Have fun

Download Links
[Play Store](https://play.google.com/store/apps/details?id=com.arduia.expense),[ F-Droid](https://f-droid.org/en/packages/com.arduia.expense)

**Comment by arduia** [comment]
@franklinbill 
Fixed: https://github.com/arduia/ProExpense/commit/afb03e3dd663e7786e87731cc042e3e6cf85e6f8

Please wait for next release.

**Comment by franklinbill** [comment]
Thanks*100000 for your reply! I think it's a good way to fix it.

**Comment by arduia** [comment]
@franklinbill You're welcome.

New version will be released soon.
Please continue your contribution. Thanks.

**Comment by franklinbill** [comment]
OK, Thank you!
