### ISSUE TITLE
Ability to delete an entry

### ISSUE THREAD

**Issue by gprst** [arduia/ProExpense#26]
### Praise part

Your application is gorgeous, has a great modern look and seems very promising. Congratulations 👏

###  Actual issue part

I can't seem to find how to delete an entry, even though I can edit it. Do you plan on making it possible, maybe on the "Edit" menu of an entry ?

**Comment by arduia** [comment]
@gprst

 Yes, whether the Delete button should exist on Edit menu or not is depend on users demand.
So I encounter your demand.

 I will consider to add this button  if multiple users (may be 100+)actually need this function. 

Thank you.

**Comment by fedaykin** [comment]
Projects with a million more users than this will very rarely get 100 +1s on an issue. How many stars does this project have?  100 people are needed (to ask) for you to approve a "delete entry" request?? We're not due this, but it's expected.  I checked here before installing and, seeing how the request to delete an entry has this high of a barrier for entry, it doesn't get installed.

**Comment by arduia** [comment]
@fedaykin 

Delete Entry feature is already exist on Expense Logs session. It is really easy to delete an entry by swiping and clicking the delete button. Also you can delete multiple items with custom selections. 

@gprst  mean that Delete Button should exist on Edit menu or not. 

Should the app behavior change according to every user request?  No, this will break all the other design and User Experience.
I don't want many star nor many application users. I just want to give a secure and safe expense note for who really  fit with this.

**Comment by arduia** [comment]
How to delete Expense Logs.
![Screenshot_2020-12-28-22-57-02-636_com arduia expense](https://user-images.githubusercontent.com/57426247/103228932-519f1400-4960-11eb-8c47-2a3233c24787.jpg)
![Screenshot_2020-12-28-22-57-06-876_com arduia expense](https://user-images.githubusercontent.com/57426247/103228937-54016e00-4960-11eb-82a6-16f2b91749e5.jpg)

**Comment by arduia** [comment]
<img src="https://user-images.githubusercontent.com/57426247/103229065-b35f7e00-4960-11eb-811b-da24248bea7d.jpg" width="300" />
<img src="(https://user-images.githubusercontent.com/57426247/103229071-b5294180-4960-11eb-90c6-4199ecbf58aa.jp" width="300" />

**Comment by arduia** [comment]
<img src="(https://user-images.githubusercontent.com/57426247/103229071-b5294180-4960-11eb-90c6-4199ecbf58aa.jp" width="300" />

**Comment by fedaykin** [comment]
Thanks for clarifying!  Sometimes it's just a matter of getting used to the UI!

**Comment by arduia** [comment]
@fedaykin

 You're welcome. The app is not stable yet! So, please try it and give me the feedback whatever you want for the app.

Thanks

**Comment by gprst** [comment]
@arduia I didn't know you could delete an entry at all ! This issue is much less important than I thought indeed, since you already can delete an entry.

I think this should be told at some point, since both of @fedaykin and I didn't know this was possible. Maybe with a tutorial ?

**Comment by arduia** [comment]
@gprst 
Yeah, it is exactly need an tutorial to educate how the application work. 

I'm going to try for tutorial tips.

By the way, Thanks you for suggestions.

**Comment by gprst** [comment]
I've seen you've added a "Bin" icon that allows to delete an entry on its "Edit" menu, so I understand this issue's closed ?

**Comment by arduia** [comment]
@gprst 
OK.

I'm waiting other issues or new feature request. 

Thanks
