### ISSUE TITLE
Make reccuring expenses more clear

### ISSUE THREAD

**Issue by gprst** [arduia/ProExpense#28]
I am still wondering how to make recurring expenses. Maybe I actually made some, but it is then unclear. I think adding a field telling if an entry is a recurring expense, or something else that is visual, might help. Maybe a radio button to toggle to make an instance recurring. What do you think ?

**Comment by arduia** [comment]
@gprst 
Yes, That is why The Lock button is exist next to "Save" button. You can freely use this for recurring expenses.

**Comment by arduia** [comment]
This issue is the same question with previous issue.

You can extends our conversation at
 https://github.com/arduia/ProExpense/issues/27
