### ISSUE TITLE
Pls allow to customize the catagories

### ISSUE THREAD

**Issue by HarshBopalia** [arduia/ProExpense#59]
Currently` the categories cannot be modified, other than that this is best expense tracker I have come across by far. Keep up the awesome work!! 😀😀

**Comment by arduia** [comment]
Yes, this requirement will be in future releases. Stay tune.

Thanks for valuable feedbacks.

**Comment by arduia** [comment]
This request is related to the ticket below.
https://github.com/arduia/ProExpense/issues/30
