### ISSUE TITLE
Edit timestamp

### ISSUE THREAD

**Issue by deepu2** [arduia/ProExpense#6]
Add a way to edit the timestamp of an entry

**Comment by arduia** [comment]
Thanks @deepu2 . I will add this function for upcoming version.

**Comment by arduia** [comment]
@deepu2 Repeatable Entry Feature will be in next release. Might be available in next week.

https://github.com/arduia/ProExpense/commit/b0b5a7f8fe906a228ed6aec8527338f9a36292c0

**Comment by arduia** [comment]
@deepu2 Date Time can be updated in next release.

https://github.com/arduia/ProExpense/commit/e31c909475623da3cc65a6f29b29cbdf50b929fe
