### ISSUE TITLE
Recurring expenses

### ISSUE THREAD

**Issue by gprst** [arduia/ProExpense#7]
It might be great to be able to set recurring expenses, that would automatically be added each day/week/month/year

**Comment by arduia** [comment]
Thanks @gprst. I also think about it. will be added for next version.

**Comment by arduia** [comment]
@gprst  Repeatable Entry Feature will be in next release. Might be available in next week.

https://github.com/arduia/ProExpense/commit/b0b5a7f8fe906a228ed6aec8527338f9a36292c0
