### ISSUE TITLE
Ability to choose more currencies

### ISSUE THREAD

**Issue by gprst** [arduia/ProExpense#8]
It would be convenient to be able to choose between USD/GBP/EUR/AUD/CAD/CHF/YEN/CNY/NZD/...

**Comment by arduia** [comment]
Thanks @gprst .

**Comment by gprst** [comment]
Thank _you_, your apps looks gorgeous and seems very promising :)

**Comment by arduia** [comment]
@gprst. Still need to improve UI design and app domain logic.

You can request other features suitable for this app. Thanks.

**Comment by arduia** [comment]
@gprst added in https://github.com/arduia/ProExpense/commit/d56c31f1e165fe16f799ccfec68834768765acd8.

Next release will be at 20th December 2020. Please wait for it. 

Thanks.

**Comment by Oymate** [comment]
Just to remind Bangladeshi taka us still not included .

**Comment by arduia** [comment]
@Oymate I have no idea Taka. Can you provide Taka currency detail info for next version release?

Info must contain following- 
  1. Currency Name (eg. "United State Dollar"),
  2. Code (eg. "USD")
  3. Symbol  (eg. "$")
  4. Number ( "840")

Thanks.

**Comment by Oymate** [comment]
1. Bangladeshi Taka
2. BDT
3. ৳
4. If you are talking about Unicode(U+09F3), HTML(&#2547;), 
Side note: general conversion rate 1 USD -> 84.8 BDT

**Comment by arduia** [comment]
@Oymate 
I Just add BDT currency that will be in next release.
https://github.com/arduia/ProExpense/commit/344eb8606c4cc95902c7288ee92546bcca96561e
