### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by licaon-kter** [arduia/ProExpense#81]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5889865982#L1499

I've bypassed them now via https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.arduia.expense.yml#L51 but maybe that's not a good thing

**Comment by arduia** [comment]
Hi @licaon-kter . I will also fix lint error on next release. Thank you!

**Comment by arduia** [comment]
AGP version is updated! Thanks to @licaon-kter. Let me close this issue.
